name: DEPLOY

on: push

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.SERVER_NAME }}
        FTP_USERNAME: ${{ secrets.SERVER_USER }}
        FTP_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        REMOTE_DIR: /srv/users/projects/apps/dev/public/wp-content/plugins/bb_commander
        ARGS: --delete
        PORT: 22
        METHOD: sftp
       
